version: "3.8"
services:
  oengus:
    container_name: oengus-backend
    build:
      context: .
    ports:
      - "8080:8080"
    network_mode: "host"
    environment:
      - SPRING_PROFILE=local
      - JWT_SECRET="<random string>"
      - PAYPAL_CLIENT_ID= # Unrequired if you don't work on donations
      - PAYPAL_CLIENT_SECRET= #Unrequired if you don't work on donations
      - DISCORD_CLIENT_ID=
      - DISCORD_CLIENT_SECRET=
      - DISCORD_BOT_TOKEN=
      - TWITCH_CLIENT_ID=
      - TWITCH_CLIENT_SECRET=
      - TWITTER_CONSUMER_KEY=
      - TWITTER_CONSUMER_SECRET=
      - TWITTER_ACCESS_TOKEN=
      - TWITTER_ACCESS_TOKEN_SECRET=
      - DB_URL=jdbc:postgresql://localhost:5432/oengus
      - DB_USERNAME=
      - DB_PASSWORD=
      - BASE_URL=http://localhost:4200
