oengus:
    jwt:
        secret: ${JWT_SECRET}
        expiration: 604800
    baseUrl: ${BASE_URL}
    oauthOrigins: ${OAUTH_ORIGINS}
    shortUrl: "https://oengus.fun"

discord:
    clientId: ${DISCORD_CLIENT_ID}
    clientSecret: ${DISCORD_CLIENT_SECRET}
    grantType: 'authorization_code'
    redirectUri: '/login/discord'
    syncRedirectUri: '/user/settings/sync/discord'
    scope:
        - identify
    botTokenRaw: ${DISCORD_BOT_TOKEN}
    botToken: 'Bot ${DISCORD_BOT_TOKEN}'

twitter:
    loginCallback: '/login/twitter'
    syncCallback: '/user/settings/sync/twitter'
    oauth:
        consumerKey: ${TWITTER_CONSUMER_KEY}
        consumerSecret: ${TWITTER_CONSUMER_SECRET}
        accessToken: ${TWITTER_ACCESS_TOKEN}
        accessTokenSecret: ${TWITTER_ACCESS_TOKEN_SECRET}

paypal:
    clientId: ${PAYPAL_CLIENT_ID}
    clientSecret: ${PAYPAL_CLIENT_SECRET}

twitch:
    login:
        clientId: ${TWITCH_CLIENT_ID}
        clientSecret: ${TWITCH_CLIENT_SECRET}
        grantType: 'authorization_code'
        redirectUri: '/login/twitch'
        syncRedirectUri: '/user/settings/sync/twitch'
        scope:
            - openid
    sync:
        clientId: ${TWITCH_CLIENT_ID}
        clientSecret: ${TWITCH_CLIENT_SECRET}
        grantType: 'authorization_code'
        syncRedirectUri: '${BASE_URL}/user/settings/sync/twitch'
        scope:
            - openid

server:
    undertow:
        accesslog:
            enabled: false

spring:
#    cache:
#        type: none
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
        properties:
            javax:
                persistence:
                    sharedCache:
                        mode: ENABLE_SELECTIVE
            hibernate:
                javax:
                    cache:
                        missing_cache_strategy: create
                cache:
                    # disable database caching
                    use_second_level_cache: false
                    use_query_cache: false
                    provider: org.ehcache.jsr107.EhcacheCachingProvider
                    region:
                        factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
                dialect: org.hibernate.dialect.PostgreSQL82Dialect
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                temp:
                    use_jdbc_metadata_defaults: false
        open-in-view: true
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        hikari:
            # Use 4 connections and leave the others for other applications
            maximum-pool-size: 4
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml
    jackson:
        mapper:
            DEFAULT_VIEW_INCLUSION: true
        deserialization:
            USE_BIG_DECIMAL_FOR_FLOATS: true

management:
    endpoints:
        web:
            exposure:
                include:
                    - prometheus
                    - health

log4j:
    logger:
        org:
            hibernate: info
